import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { UserDetailProvider } from "./_context/UserDetailContext";
import ToasterProvider from "./_components/ToasterProvider";
import { ThemeProvider } from "./_context/ThemeContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
        >
          <ThemeProvider>
            <UserDetailProvider>
              {children}
            </UserDetailProvider>
          </ThemeProvider>
          <ToasterProvider />



        </body>
      </html>
    </ClerkProvider>
  );
}
